![logo_ironhack_blue 7](https://user-images.githubusercontent.com/23629340/40541063-a07a0a8a-601a-11e8-91b5-2f13e4e6b441.png)

# Lab | Random variable distributions

Refer to the `files_for_lab/we_fn_use_c_marketing_customer_value_analysis.csv` dataset.

### Instructions

1. Get the numerical variables from our dataset.
2. Check using a distribution plot if the variables fit the theoretical normal or exponential distribution.
3. Check if any of the transformations (log-transform, etc.) we have seen up to this point changes the result.

In [1]:
import pandas as pd
import numpy as np
import snakecase
import stringcase
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

#### 1. Get the numerical variables from our dataset.
***

In [2]:
numerical = pd.read_csv('numericalsfinal.csv')
numerical.drop(['Unnamed: 0'],axis=1,inplace=True)
numerical

,customer__lifetime__value,income,monthly__premium__auto,months__since__last__claim,months__since__policy__inception,number_of__open__complaints,number_of__policies,total__claim__amount
0,2763.519279,56274,69,32,5,0,1,384.811147
1,6979.535903,0,94,13,42,0,8,1131.464935
2,12887.431650,48767,108,18,38,0,2,566.472247
3,7645.861827,0,106,18,65,0,7,529.881344
4,2813.692575,43836,73,12,44,0,1,138.130879
...,...,...,...,...,...,...,...,...
9129,23405.987980,71941,73,18,89,0,2,198.234764
9130,3096.511217,21604,79,14,28,0,1,379.200000
9131,8163.890428,0,85,9,37,3,2,790.784983
9132,7524.442436,21941,96,34,3,0,3,691.200000
9133,2611.836866,0,77,3,90,0,1,369.600000

#### 2. Check using a distribution plot if the variables fit the theoretical normal or exponential distribution.
***

In [3]:
for col in data:
    plt.hist(data[col], bins=10)
    plt.title(col)
    plt.show()

NameError: name 'data' is not defined

In [11]:
data = pd.read_csv('/Users/joao/Desktop/Ironhack/Mid Project/Data/mid_project_weather_data.csv')

In [12]:
sorted(data['name'].unique())

['amsterdam',
 'athens',
 'belgrade',
 'berlin',
 'bern',
 'brussels',
 'bucharest',
 'budapest',
 'copenhagen',
 'dublin',
 'helsinki',
 'kyiv',
 'lisbon',
 'ljubljana',
 'london',
 'luxembourg',
 'madrid',
 'minsk',
 'oslo',
 'paris',
 'podgoica',
 'prague',
 'reykjavik',
 'rome',
 'sarajevo',
 'skopje',
 'sofia',
 'stockholm',
 'tallinn',
 'tirana',
 'valletta',
 'vienna',
 'vilnius',
 'warsaw',
 'zagreb']